import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
import Provider from '@/components/Provider';
import { ThemeProvider } from '@/components/ThemeProvider';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export const dynamic = 'force-static';

export default function RootLayout({ children }) {
    return (
        <Provider>
            <html lang="en">
                <body className={inter.className}>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                        {children}
                    </ThemeProvider>
                </body>
            </html>
        </Provider>
    );
}
